/**
 * Curated GeeksforGeeks-style metadata (manual refresh). Do not scrape GFG live.
 * Titles and summaries are abbreviated; candidates use externalUrl for full statements.
 */
export const GFG_CURATED_PROBLEMS = [
  {
    id: "gfg-01-two-sum",
    title: "Two Sum (pair with given sum)",
    difficulty: "easy",
    topics: ["arrays", "hashmap"],
    statement:
      "Given an array of integers and a target sum, return whether a pair exists that sums to the target. Practice the efficient approach on the linked page.",
    constraints: ["Array length up to large N per problem page"],
    sampleInput: "arr = [1, 4, 45, 6, 10, 8], target = 16",
    sampleOutput: "true",
    timeLimitSeconds: 2700,
    hints: ["Hash map of seen values", "Sort + two pointers variant"],
    companies: ["Amazon"],
    starterCode: {
      javascript: "function twoSumExists(arr, target) {\n  return false;\n}\n",
      python: "def two_sum_exists(arr, target):\n    return False\n",
      cpp: "bool twoSumExists(vector<int>& arr, int target) {\n  return false;\n}\n",
      java: "class Solution {\n    public boolean twoSumExists(int[] arr, int target) {\n        return false;\n    }\n}\n",
    },
    problemSource: "gfg",
    externalUrl: "https://www.geeksforgeeks.org/check-if-pair-with-given-sum-exists-in-the-array-or-not/",
    hasAutomatedTests: false,
  },
  {
    id: "gfg-02-reverse-linked-list",
    title: "Reverse a linked list",
    difficulty: "easy",
    topics: ["linked-list"],
    statement:
      "Reverse a singly linked list in-place. Master both iterative and recursive patterns using the article.",
    constraints: ["List size per GFG constraints"],
    sampleInput: "1 -> 2 -> 3 -> NULL",
    sampleOutput: "3 -> 2 -> 1 -> NULL",
    timeLimitSeconds: 2700,
    hints: ["Three-pointer iterative", "Recursion with rest reversed"],
    companies: ["Microsoft", "Adobe"],
    starterCode: {
      javascript:
        "function reverseList(head) {\n  return null;\n}\n",
      python: "def reverse_list(head):\n    return None\n",
      cpp: "ListNode* reverseList(ListNode* head) {\n    return nullptr;\n}\n",
      java: "class Solution {\n    public ListNode reverseList(ListNode head) {\n        return null;\n    }\n}\n",
    },
    problemSource: "gfg",
    externalUrl: "https://www.geeksforgeeks.org/reverse-a-linked-list/",
    hasAutomatedTests: false,
  },
  {
    id: "gfg-03-binary-tree-inorder",
    title: "Binary Tree Inorder Traversal",
    difficulty: "easy",
    topics: ["trees", "dfs"],
    statement:
      "Return the inorder traversal of a binary tree's node values. Implement iterative and recursive solutions.",
    constraints: ["Node count per problem statement"],
    sampleInput: "root of a binary tree",
    sampleOutput: "inorder list of values",
    timeLimitSeconds: 2700,
    hints: ["Left, root, right", "Stack for iterative"],
    companies: ["Google"],
    starterCode: {
      javascript: "function inorderTraversal(root) {\n  return [];\n}\n",
      python: "def inorder_traversal(root):\n    return []\n",
      cpp: "vector<int> inorderTraversal(TreeNode* root) {\n    return {};\n}\n",
      java: "class Solution {\n    public List<Integer> inorderTraversal(TreeNode root) {\n        return new ArrayList<>();\n    }\n}\n",
    },
    problemSource: "gfg",
    externalUrl: "https://www.geeksforgeeks.org/inorder-tree-traversal-without-recursion-and-with-recursion/",
    hasAutomatedTests: false,
  },
  {
    id: "gfg-04-lcs",
    title: "Longest Common Subsequence",
    difficulty: "medium",
    topics: ["dynamic-programming", "strings"],
    statement:
      "Given two strings, find the length of their longest common subsequence.",
    constraints: ["Classic DP constraints on GFG page"],
    sampleInput: 's1 = "ABCDGH", s2 = "AEDFHR"',
    sampleOutput: "3",
    timeLimitSeconds: 2700,
    hints: ["2D DP table", "Match vs skip"],
    companies: ["Flipkart"],
    starterCode: {
      javascript: "function lcs(s1, s2) {\n  return 0;\n}\n",
      python: "def lcs(s1, s2):\n    return 0\n",
      cpp: "int lcs(string& s1, string& s2) {\n    return 0;\n}\n",
      java: "class Solution {\n    public int lcs(String s1, String s2) {\n        return 0;\n    }\n}\n",
    },
    problemSource: "gfg",
    externalUrl: "https://www.geeksforgeeks.org/longest-common-subsequence-dp-using-memoization/",
    hasAutomatedTests: false,
  },
  {
    id: "gfg-05-dijkstra",
    title: "Dijkstra shortest path",
    difficulty: "medium",
    topics: ["graphs", "shortest-path"],
    statement:
      "Find shortest paths from a source vertex in a weighted graph with non-negative edges.",
    constraints: ["Graph size per GFG"],
    sampleInput: "weighted graph, source vertex",
    sampleOutput: "shortest distances",
    timeLimitSeconds: 2700,
    hints: ["Priority queue / min-heap", "Relax edges"],
    companies: ["Uber"],
    starterCode: {
      javascript: "function dijkstra(graph, src) {\n  return [];\n}\n",
      python: "def dijkstra(graph, src):\n    return []\n",
      cpp: "vector<int> dijkstra(vector<vector<pair<int,int>>>& graph, int src) {\n    return {};\n}\n",
      java: "class Solution {\n    public int[] dijkstra(List<List<int[]>> graph, int src) {\n        return new int[]{};\n    }\n}\n",
    },
    problemSource: "gfg",
    externalUrl: "https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/",
    hasAutomatedTests: false,
  },
];
