import { PROBLEM_POOL } from "./problemPool.js";

export const PROBLEM_METADATA_OVERRIDES = {
  "two-sum-signals": {
    hasAutomatedTests: true,
    idealTimeComplexity: "O(n)",
    idealSpaceComplexity: "O(n)",
    roleTags: ["software-engineer", "backend", "frontend", "full-stack", "qa"],
  },
  "valid-parentheses-flow": {
    hasAutomatedTests: true,
    idealTimeComplexity: "O(n)",
    idealSpaceComplexity: "O(n)",
    roleTags: ["software-engineer", "frontend", "qa", "security"],
  },
  "merge-intervals-room-plan": {
    hasAutomatedTests: true,
    idealTimeComplexity: "O(n log n)",
    idealSpaceComplexity: "O(n)",
    roleTags: ["software-engineer", "backend", "devops", "product"],
  },
  "product-array-stream": {
    hasAutomatedTests: true,
    idealTimeComplexity: "O(n)",
    idealSpaceComplexity: "O(1)",
    roleTags: ["software-engineer", "backend", "data-science", "data-engineering"],
  },
  "longest-substring-signal": {
    hasAutomatedTests: true,
    idealTimeComplexity: "O(n)",
    idealSpaceComplexity: "O(n)",
    roleTags: ["software-engineer", "frontend", "mobile", "qa"],
  },
  "kth-largest-stream": {
    hasAutomatedTests: true,
    idealTimeComplexity: "O(n log k)",
    idealSpaceComplexity: "O(k)",
    roleTags: ["software-engineer", "backend", "data-science", "data-engineering"],
  },
  "clone-graph-signal-map": {
    hasAutomatedTests: false,
    idealTimeComplexity: "O(n)",
    idealSpaceComplexity: "O(n)",
    roleTags: ["software-engineer", "backend", "devops"],
  },
  "course-schedule-paths": {
    hasAutomatedTests: true,
    idealTimeComplexity: "O(n)",
    idealSpaceComplexity: "O(n)",
    roleTags: ["software-engineer", "backend", "devops", "data-engineering"],
  },
  "lru-cache-console": {
    hasAutomatedTests: false,
    idealTimeComplexity: "O(1)",
    idealSpaceComplexity: "O(n)",
    roleTags: ["software-engineer", "backend"],
  },
  "word-ladder-router": {
    hasAutomatedTests: true,
    idealTimeComplexity: "O(n^2)",
    idealSpaceComplexity: "O(n)",
    roleTags: ["software-engineer", "backend", "security", "devops"],
  },
  "median-data-stream": {
    hasAutomatedTests: false,
    idealTimeComplexity: "O(log n)",
    idealSpaceComplexity: "O(n)",
    roleTags: ["software-engineer", "backend", "data-science"],
  },
  "trapping-rain-ops": {
    hasAutomatedTests: true,
    idealTimeComplexity: "O(n)",
    idealSpaceComplexity: "O(1)",
    roleTags: ["software-engineer", "backend", "qa", "mobile"],
  },
};

export const EXTRA_PROBLEMS = [
  {
    id: "best-time-stock-window",
    title: "Best Time Stock Window",
    difficulty: "easy",
    topics: ["arrays", "greedy"],
    roleTags: ["software-engineer", "data-science", "data-engineering", "product"],
    statement:
      "Given an array where prices[i] is the stock price on day i, return the maximum profit you can achieve from one buy and one sell. Return 0 if no profit is possible.",
    constraints: ["1 <= prices.length <= 10^5", "0 <= prices[i] <= 10^4"],
    sampleInput: "prices = [7,1,5,3,6,4]",
    sampleOutput: "5",
    timeLimitSeconds: 2700,
    hasAutomatedTests: true,
    idealTimeComplexity: "O(n)",
    idealSpaceComplexity: "O(1)",
    hints: ["Track the lowest price so far", "Update best profit greedily"],
    companies: ["Amazon", "Microsoft"],
    starterCode: {
      javascript: "function maxProfit(prices) {\n  return 0;\n}\n",
      python: "def max_profit(prices):\n    return 0\n",
      cpp: "int maxProfit(vector<int>& prices) {\n  return 0;\n}\n",
      java: "class Solution {\n    public int maxProfit(int[] prices) {\n        return 0;\n    }\n}\n",
    },
  },
  {
    id: "valid-anagram-check",
    title: "Valid Anagram Check",
    difficulty: "easy",
    topics: ["strings", "hashmap"],
    roleTags: ["software-engineer", "frontend", "qa", "security"],
    statement:
      "Given two strings s and t, return true if t is an anagram of s and false otherwise.",
    constraints: ["1 <= s.length, t.length <= 5 * 10^4"],
    sampleInput: 's = "anagram", t = "nagaram"',
    sampleOutput: "true",
    timeLimitSeconds: 2700,
    hasAutomatedTests: true,
    idealTimeComplexity: "O(n)",
    idealSpaceComplexity: "O(n)",
    hints: ["Count characters", "Compare frequency maps"],
    companies: ["Meta", "Spotify"],
    starterCode: {
      javascript: "function isAnagram(s, t) {\n  return false;\n}\n",
      python: "def is_anagram(s, t):\n    return False\n",
      cpp: "bool isAnagram(string s, string t) {\n  return false;\n}\n",
      java: "class Solution {\n    public boolean isAnagram(String s, String t) {\n        return false;\n    }\n}\n",
    },
  },
  {
    id: "binary-search-lookup",
    title: "Binary Search Lookup",
    difficulty: "easy",
    topics: ["arrays", "binary-search"],
    roleTags: ["software-engineer", "backend", "data-engineering", "qa"],
    statement:
      "Given a sorted array of integers and a target value, return the index if the target is found, otherwise return -1.",
    constraints: ["1 <= nums.length <= 10^5"],
    sampleInput: "nums = [-1,0,3,5,9,12], target = 9",
    sampleOutput: "4",
    timeLimitSeconds: 2700,
    hasAutomatedTests: true,
    idealTimeComplexity: "O(log n)",
    idealSpaceComplexity: "O(1)",
    hints: ["Use left, right, and mid pointers", "Avoid linear scans"],
    companies: ["Google", "Atlassian"],
    starterCode: {
      javascript: "function search(nums, target) {\n  return -1;\n}\n",
      python: "def search(nums, target):\n    return -1\n",
      cpp: "int search(vector<int>& nums, int target) {\n  return -1;\n}\n",
      java: "class Solution {\n    public int search(int[] nums, int target) {\n        return -1;\n    }\n}\n",
    },
  },
  {
    id: "maximum-subarray-beacon",
    title: "Maximum Subarray Beacon",
    difficulty: "medium",
    topics: ["arrays", "dynamic-programming"],
    roleTags: ["software-engineer", "data-science", "product", "mobile"],
    statement:
      "Given an integer array nums, find the contiguous subarray with the largest sum and return that sum.",
    constraints: ["1 <= nums.length <= 10^5", "-10^4 <= nums[i] <= 10^4"],
    sampleInput: "nums = [-2,1,-3,4,-1,2,1,-5,4]",
    sampleOutput: "6",
    timeLimitSeconds: 2700,
    hasAutomatedTests: true,
    idealTimeComplexity: "O(n)",
    idealSpaceComplexity: "O(1)",
    hints: ["Kadane's algorithm", "Track best ending here"],
    companies: ["Amazon", "Bloomberg"],
    starterCode: {
      javascript: "function maxSubArray(nums) {\n  return 0;\n}\n",
      python: "def max_sub_array(nums):\n    return 0\n",
      cpp: "int maxSubArray(vector<int>& nums) {\n  return 0;\n}\n",
      java: "class Solution {\n    public int maxSubArray(int[] nums) {\n        return 0;\n    }\n}\n",
    },
  },
  {
    id: "search-rotated-index",
    title: "Search Rotated Index",
    difficulty: "medium",
    topics: ["arrays", "binary-search"],
    roleTags: ["software-engineer", "backend", "data-engineering", "qa"],
    statement:
      "You are given a sorted array that has been rotated at an unknown pivot. Return the index of target if it exists, otherwise -1.",
    constraints: ["1 <= nums.length <= 5 * 10^4"],
    sampleInput: "nums = [4,5,6,7,0,1,2], target = 0",
    sampleOutput: "4",
    timeLimitSeconds: 2700,
    hasAutomatedTests: true,
    idealTimeComplexity: "O(log n)",
    idealSpaceComplexity: "O(1)",
    hints: ["One half is always sorted", "Use binary-search branching"],
    companies: ["Meta", "Uber"],
    starterCode: {
      javascript: "function searchRotated(nums, target) {\n  return -1;\n}\n",
      python: "def search_rotated(nums, target):\n    return -1\n",
      cpp: "int searchRotated(vector<int>& nums, int target) {\n  return -1;\n}\n",
      java: "class Solution {\n    public int searchRotated(int[] nums, int target) {\n        return -1;\n    }\n}\n",
    },
  },
  {
    id: "daily-temperatures-queue",
    title: "Daily Temperatures Queue",
    difficulty: "medium",
    topics: ["stack", "arrays"],
    roleTags: ["software-engineer", "frontend", "qa", "mobile"],
    statement:
      "Given a list of daily temperatures, return an array such that each index tells how many days you must wait to get a warmer temperature. Return 0 when no warmer day exists.",
    constraints: ["1 <= temperatures.length <= 10^5"],
    sampleInput: "temperatures = [73,74,75,71,69,72,76,73]",
    sampleOutput: "[1,1,4,2,1,1,0,0]",
    timeLimitSeconds: 2700,
    hasAutomatedTests: true,
    idealTimeComplexity: "O(n)",
    idealSpaceComplexity: "O(n)",
    hints: ["Monotonic stack", "Resolve earlier colder days when you see a warmer one"],
    companies: ["Amazon", "DoorDash"],
    starterCode: {
      javascript: "function dailyTemperatures(temperatures) {\n  return [];\n}\n",
      python: "def daily_temperatures(temperatures):\n    return []\n",
      cpp: "vector<int> dailyTemperatures(vector<int>& temperatures) {\n  return {};\n}\n",
      java: "class Solution {\n    public int[] dailyTemperatures(int[] temperatures) {\n        return new int[]{};\n    }\n}\n",
    },
  },
  {
    id: "coin-change-budget",
    title: "Coin Change Budget",
    difficulty: "medium",
    topics: ["dynamic-programming", "arrays"],
    roleTags: ["software-engineer", "data-science", "mobile", "product"],
    statement:
      "Given coin denominations and a total amount, return the fewest number of coins required to make the amount. Return -1 when it is impossible.",
    constraints: ["1 <= coins.length <= 12", "0 <= amount <= 10^4"],
    sampleInput: "coins = [1,2,5], amount = 11",
    sampleOutput: "3",
    timeLimitSeconds: 2700,
    hasAutomatedTests: true,
    idealTimeComplexity: "O(n^2)",
    idealSpaceComplexity: "O(n)",
    hints: ["Bottom-up DP works well", "Initialize impossible states carefully"],
    companies: ["Microsoft", "Google"],
    starterCode: {
      javascript: "function coinChange(coins, amount) {\n  return -1;\n}\n",
      python: "def coin_change(coins, amount):\n    return -1\n",
      cpp: "int coinChange(vector<int>& coins, int amount) {\n  return -1;\n}\n",
      java: "class Solution {\n    public int coinChange(int[] coins, int amount) {\n        return -1;\n    }\n}\n",
    },
  },
  {
    id: "house-robber-lane",
    title: "House Robber Lane",
    difficulty: "medium",
    topics: ["dynamic-programming", "arrays"],
    roleTags: ["software-engineer", "mobile", "data-science", "product"],
    statement:
      "Given an array of non-negative integers representing money in each house, return the maximum amount you can rob without robbing adjacent houses.",
    constraints: ["1 <= nums.length <= 10^5"],
    sampleInput: "nums = [2,7,9,3,1]",
    sampleOutput: "12",
    timeLimitSeconds: 2700,
    hasAutomatedTests: true,
    idealTimeComplexity: "O(n)",
    idealSpaceComplexity: "O(1)",
    hints: ["Each house creates a rob/skip choice", "Track previous best states"],
    companies: ["Adobe", "Stripe"],
    starterCode: {
      javascript: "function rob(nums) {\n  return 0;\n}\n",
      python: "def rob(nums):\n    return 0\n",
      cpp: "int rob(vector<int>& nums) {\n  return 0;\n}\n",
      java: "class Solution {\n    public int rob(int[] nums) {\n        return 0;\n    }\n}\n",
    },
  },
  {
    id: "longest-consecutive-streak",
    title: "Longest Consecutive Streak",
    difficulty: "medium",
    topics: ["arrays", "hashmap"],
    roleTags: ["software-engineer", "backend", "data-engineering", "qa"],
    statement:
      "Given an unsorted array of integers, return the length of the longest consecutive elements sequence.",
    constraints: ["0 <= nums.length <= 10^5"],
    sampleInput: "nums = [100,4,200,1,3,2]",
    sampleOutput: "4",
    timeLimitSeconds: 2700,
    hasAutomatedTests: true,
    idealTimeComplexity: "O(n)",
    idealSpaceComplexity: "O(n)",
    hints: ["A hash set avoids sorting", "Only start counting from sequence beginnings"],
    companies: ["Google", "Databricks"],
    starterCode: {
      javascript: "function longestConsecutive(nums) {\n  return 0;\n}\n",
      python: "def longest_consecutive(nums):\n    return 0\n",
      cpp: "int longestConsecutive(vector<int>& nums) {\n  return 0;\n}\n",
      java: "class Solution {\n    public int longestConsecutive(int[] nums) {\n        return 0;\n    }\n}\n",
    },
  },
  {
    id: "minimum-window-signal",
    title: "Minimum Window Signal",
    difficulty: "hard",
    topics: ["strings", "sliding-window", "hashmap"],
    roleTags: ["software-engineer", "frontend", "backend", "security"],
    statement:
      "Given strings s and t, return the minimum window in s that contains every character in t including duplicates. Return an empty string when no such window exists.",
    constraints: ["1 <= s.length, t.length <= 10^5"],
    sampleInput: 's = "ADOBECODEBANC", t = "ABC"',
    sampleOutput: '"BANC"',
    timeLimitSeconds: 2700,
    hasAutomatedTests: true,
    idealTimeComplexity: "O(n)",
    idealSpaceComplexity: "O(n)",
    hints: ["Use a frequency map", "Shrink the left side only when valid"],
    companies: ["Meta", "Amazon"],
    starterCode: {
      javascript: "function minWindow(s, t) {\n  return \"\";\n}\n",
      python: "def min_window(s, t):\n    return \"\"\n",
      cpp: "string minWindow(string s, string t) {\n  return \"\";\n}\n",
      java: "class Solution {\n    public String minWindow(String s, String t) {\n        return \"\";\n    }\n}\n",
    },
  },
];

export function getExpandedProblemPool() {
  return [...PROBLEM_POOL, ...EXTRA_PROBLEMS].map((problem) => ({
    ...problem,
    ...(PROBLEM_METADATA_OVERRIDES[problem.id] || {}),
  }));
}
